import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {projects} from "../data/projects";
import {AiFillLinkedin} from "react-icons/ai/index";
import {BsGithub} from "react-icons/bs/index"
import Contact from "../components/Contact";
import {SiUpwork} from "react-icons/si/index"
import { SkillsServicesSection } from "../components/SkillsServicesSection";
import NewProjectCard from "../components/NewProjectCard";
import ResumeModal from "../components/ResumeModal";
import { useState } from "react";
import {FcDocument} from 'react-icons/fc/index'
import {BiHomeAlt2} from 'react-icons/bi/index'
import {IoMdCodeWorking} from 'react-icons/io/index'


const Home: NextPage = () => {
  const [openModal, setOpenModal] = useState<boolean>(false)

  const toggleModal = () => {
    setOpenModal(!openModal)
  }
  return (
    <>
      <Head>
        <title>Jalen Arms Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* <div className="h-[40rem] flex flex-col items-center  gap-8 justify-center ">
        <div className="flex flex-col gap-2 items-center justify-center text-cyan-600">
          <p className="text-6xl">Jalen Arms</p>
          <p className="text-center text-lg">Full-Stack Developer</p>
        </div>
        <div className="icons flex gap-3 text-slate-500">
          <Link href={"https://www.linkedin.com/in/jalen-arms-38304a241"} target="_blank" className="hover:text-cyan-600">
            <AiFillLinkedin className="text-4xl" />
          </Link>
          <Link href={"https://github.com/jalenarms1"} target="_blank" className="hover:text-cyan-600">
            <BsGithub className="text-4xl" />
          </Link>
          <Link href={"https://www.upwork.com/freelancers/~01cd6b779e11f90eb8"} target="_blank" className="hover:text-cyan-600">
            <SiUpwork className="text-4xl" />
          </Link>
        </div>
        <Contact />

      </div> */}
      <nav className="absolute px-10 top-0 left-0 w-full z-50">
        <div className="">
          <div className="flex items-center justify-between py-4">
            <button onClick={toggleModal} className="text-lg text-gray-900 font-bold bg-gray-100 hover:bg-gray-400 rounded-full transition-colors px-4 py-2 flex items-center gap-1">
              <FcDocument />
              <p>Resume</p>
            </button>
            
            <div className="flex items-center">
              <Link href="/about"className={`text-white hover:text-gray-300 px-4 flex items-center gap-1`}>
                <BiHomeAlt2 />
                <p>Home</p>
              </Link>
              <Link href="/about"className="text-white hover:text-gray-300 px-4 flex items-center gap-1">
                <IoMdCodeWorking />
                <p>Projects</p>
              </Link>
              {/* <Link href="/about"className="text-white hover:text-gray-300 px-4 flex items-center gap-1">
                <BsGithub />
                <p>Github</p>
              </Link> */}
            </div>
          </div>
        </div>
      </nav>
      <section className="hero bg-cover bg-center flex justify-between" style={{ backgroundImage: 'linear-gradient(to bottom, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, .85)), url("https://res.cloudinary.com/dvlhy87zl/image/upload/v1679852321/dynamic-wavy-line-colorful-background_67845-1117_jiumzc.jpg")'}}>
        <div className=" w-[90%] mx-auto pt-40 pb-20">
          <div className="flex flex-col">
            <h1 className="text-5xl font-bold text-white leading-tight ">
              Jalen Arms
            </h1>
            <a className=" text-gray-300 hover:text-blue-500" href="mailto:jalenarms@outlook.com text-xs">Email: jalenarms@outlook.com</a>
            <div className="icons flex gap-3 text-gray-300 my-2">
              <Link href={"https://www.linkedin.com/in/jalen-arms-38304a241"} target="_blank" className="hover:text-blue-600">
                <AiFillLinkedin className="text-4xl" />
              </Link>
              <Link href={"https://github.com/jalenarms1"} target="_blank" className="hover:text-blue-600">
                <BsGithub className="text-4xl" />
              </Link>
              <Link href={"https://www.upwork.com/freelancers/~01cd6b779e11f90eb8"} target="_blank" className="hover:text-blue-600">
                <SiUpwork className="text-4xl" />
              </Link>
            </div>
          </div>
            <div className="py-3"></div>
          <p className="text-xl text-white leading-tight mb-5">
            Full-stack Software Developer.
          </p>
          <p className="text-sm text-white leading-tight mb-12">
           Angular | ASP.NET 6 | React JS | Next.js |  Node.js | Python | SQL Server
          </p>
          {/* <button className="bg-white text-gray-900 py-3 px-6 rounded-full hover:bg-purple-400 transition-colors">
            Learn More
          </button> */}
        </div>
        
      </section>
      {/* <SkillsServicesSection /> */}
      <section className="bg-gray-900 py-10">
        <div className=" mx-auto w-[90%]">
          <h2 className="text-5xl w-fit  text-gray-100 font-bold border-b border-gray-700 shadow-inner shadow-gray-900 px-4 py-5 ">Projects</h2>
          <p className="text-sx mt-4 mb-10 text-gray-500">(Click on any image or title to view the deployed application)</p>
          <div className="flex flex-col gap-16">
            {projects.slice(0,3).map((proj, index) => (
              <NewProjectCard key={index} proj={proj} />
          
            ))}
            <div className="see-more-btn w-full flex justify-center py-8" id="see-more-btn">
              <button className="w-1/4 px-3 py-2 bg-gray-300 hover:bg-gray-200 active:bg-gray-300 rounded-md text-gray-900">
                See More
              </button>
            </div>
            
            
            
          </div>
          
        </div>
      </section>
      {openModal ? <ResumeModal toggleModal={toggleModal} /> : null}
      


      




    
      
    </>
  );
};

export default Home;
