import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { trpc } from "../utils/trpc";

const proj = {
  title: `Shop Shop`,
  imageUrl: `https://res.cloudinary.com/dvlhy87zl/image/upload/v1671233451/shopimg_cjfwih.png`,
  liveUrl: `https://mysterious-brushlands-70155.herokuapp.com/`,
  languages: 'React JS, Node.js, GraphQL, MongoDB / Mongoose, JWT',
  githubUrl: `https://github.com/zhaihan001/Team-Project3-Shop-Shop`
}

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="contain-app w-full h-screen bg-gray-800">
        <nav className="w-full bg-slate-900 h-16 flex justify-center text-slate-500">
          <div className="nav-right mr-5">
            <ul className="flex transition-shadow">
              <li className="cursor-pointer shadow-inner hover:shadow-slate-500 p-5 hover:bg-gray-700 active:bg-gray-800 hover:text-gray-300 hover:transition-colors">
                Projects
              </li>
              <li className="cursor-pointer shadow-inner hover:shadow-slate-500 p-5 hover:bg-gray-700 active:bg-gray-800 hover:text-gray-300 hover:transition-colors">
                {/* <Image src={"/images/edit-1.1s-200px (1).png"} alt={"education"} width={20} height={25} /> */}
                Education
              </li>
              <li className="cursor-pointer shadow-inner hover:shadow-slate-500 p-5 hover:bg-gray-700 active:bg-gray-800 hover:text-gray-300 hover:transition-colors">
                Resume
              </li>
              <li className="cursor-pointer shadow-inner hover:shadow-slate-500 p-5 hover:bg-gray-700 active:bg-gray-800 hover:text-gray-300 hover:transition-colors">
                GitHub
              </li>
            </ul>
          </div>
        </nav>

        <div className="wrap-projects flex gap-10 justify-center pt-10">
          <div className="proj">
            <div className="card-img border-b border-gray-300 pb-12">
              <Image src={proj.imageUrl} alt={"proj-img"} width={500} height={400} className="rounded shadow-lg shadow-slate-500 " />

            </div>
            <div className="card-body text-slate-50 flex flex-col items-center py-2 gap-3">
              <h4 className="text-2xl">{proj.title}</h4>
              <p className="text-xs">{proj.languages}</p>

            </div>

          </div>

        </div>

      </div>
    </>
  );
};

export default Home;
